//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauGia.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Img { get; set; }
        public byte Type { get; set; }
        public int Quantity { get; set; }
        public System.DateTime TimeUpdate { get; set; }
        public byte Status { get; set; }
        public int UserId { get; set; }
        public bool Active { get; set; }
    
        public virtual ProductStatu ProductStatu { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual User User { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
